project:
  type: website
  output-dir: docs

website:
  title: "Sara Gonzalez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    background: light
    left:
      "Copyright 2023, Sara Gonzalez"
format:
  html:
    theme: mystyles.scss
    css: styles.css
    mainfont: Lexend
    toc: true



