---
title: "travel"
subtitle: "my travelling adventures"
---

As someone who is of different ethnicities, it is safe to say that I have traveled quite a bit. I used to go to Mexico pretty regularly with my dad. However, he would often go during the school year, meaning that as I got older, school started getting in the way of traveling and I couldn't go as often as I wanted to. I went from going at least once a year or every other year to not being there in nearly 5 years. Granted, COVID happened, but my point still stands.

Unfortunately, I have yet to go to Japan. I have been wanting to go ever since I was a little girl, probably about 5 or so. I plan to go to Japan to celebrate graduating from college, specifically Osaka, Hiroshima, Tokyo, and Okinawa. I probably won't be able to go to all 4 places in one trip, but hopefully I can go to 2.

In recent times, I have some relatives in Las Vegas, so I've gone there several times within the last year. Although there are a lot of things in Vegas that I can't do until I'm 21, I still like going there to visit family, eat good food, and shop (since the sales tax is lower).
